# Generated by Django 4.2 on 2024-12-04 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_alter_booking_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmhouseimage',
            name='image',
            field=models.ImageField(upload_to='./farmhouse_images/'),
        ),
    ]
