# Generated by Django 4.2 on 2024-12-04 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_alter_farmhouseimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmhouseimage',
            name='image',
            field=models.ImageField(upload_to='listings/static/images/'),
        ),
    ]
