# Generated by Django 4.2 on 2024-12-04 03:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_alter_farmhouseimage_image'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='farmhousepricing',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='farmhousepricing',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='farmhousepricing',
            unique_together={('farmhouse', 'date', 'shift')},
        ),
        migrations.RemoveField(
            model_name='farmhousepricing',
            name='month',
        ),
        migrations.RemoveField(
            model_name='farmhousepricing',
            name='year',
        ),
    ]
