# Generated by Django 4.2 on 2024-12-24 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_alter_farmhousepricing_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_number',
            field=models.CharField(editable=False, max_length=35, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together={('farmhouse', 'booking_date', 'shift')},
        ),
    ]
