# Generated by Django 4.2 on 2024-12-24 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpaymentledger',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userrechargehistory',
            name='package',
        ),
        migrations.RemoveField(
            model_name='userrechargehistory',
            name='user',
        ),
        migrations.DeleteModel(
            name='AllUser',
        ),
        migrations.DeleteModel(
            name='Package',
        ),
        migrations.DeleteModel(
            name='UserPaymentLedger',
        ),
        migrations.DeleteModel(
            name='UserRechargeHistory',
        ),
    ]
